import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import WorkoutsProviders from "@/context/WorkoutsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fitlog - Workout Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="min-h-full flex flex-col  bg-black">
        <WorkoutsProviders>
          <Navbar></Navbar>
          <div className="divider -mt-2"></div>
        {children}
        <div className="divider"></div>
        <Footer></Footer>
        <ToastContainer />
        </WorkoutsProviders>
      </body>
    </html>
  );
}
